#!/usr/bin/env python3
"""Generate MP3 audio for an Arabic flashcard deck.

Reads a cards.json manifest, synthesises audio for each headword and each
example sentence, and writes MP3 files to the output directory.

Providers:
    gtts        — default, free, no API key (pip install gTTS)
    elevenlabs  — higher quality, requires ELEVENLABS_API_KEY
                  (pip install elevenlabs)

Network-restricted environments:
    If gTTS cannot reach translate.google.com (common in sandboxed
    environments with allowlists), no silent placeholders are created.
    Instead, a standalone `regen_audio.py` is dropped next to the deck
    so the user can synthesise audio later on a machine with normal
    internet access. Override with --no-regen-script.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import textwrap
from pathlib import Path

REGEN_SCRIPT_TEMPLATE = r'''#!/usr/bin/env python3
"""Regenerate MP3 audio for this deck using gTTS.

Auto-generated by the arabic-flashcards plugin when sandbox synthesis failed.
Run on a machine with normal internet access.

Requirements:
    pip install gTTS

Usage:
    python regen_audio.py
"""
import json
import sys
from pathlib import Path

try:
    from gtts import gTTS
except ImportError:
    print("gTTS not installed. Run:  pip install gTTS")
    sys.exit(1)

HERE = Path(__file__).parent
MANIFEST = HERE / "cards.json"
AUDIO_DIR = HERE / "audio"
AUDIO_DIR.mkdir(exist_ok=True)

LANG = "ar"  # Modern Standard Arabic voice (closest match for Najdi too)


def synth(text, out):
    gTTS(text=text, lang=LANG, slow=False).save(str(out))


def main():
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    cards = data["cards"]
    n = 0
    for c in cards:
        slug = c["slug"]
        synth(c["arabic"], AUDIO_DIR / f"{slug}.mp3"); n += 1
        for i, s in enumerate(c["sentences"], start=1):
            synth(s["ar"], AUDIO_DIR / f"{slug}_ex{i}.mp3"); n += 1
        print(f"  {c['arabic']}  ({slug})")
    print(f"\n[OK] {n} MP3 files in {AUDIO_DIR}")


if __name__ == "__main__":
    main()
'''

REGEN_BAT_TEMPLATE = r'''@echo off
REM ============================================================
REM  Arabic flashcards - one-click audio generator (Windows)
REM  Double-click this file or run from PowerShell/cmd.
REM  Requires: Python 3.x installed and on PATH.
REM ============================================================

setlocal
cd /d "%~dp0"

echo.
echo ============================================================
echo  Arabic Flashcards - Audio Generator
echo  Deck folder: %CD%
echo ============================================================
echo.

python --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python was not found on your PATH.
    echo         Install it from https://www.python.org/downloads/
    echo         During install, TICK "Add Python to PATH".
    echo         Then close this window and run this script again.
    echo.
    pause
    exit /b 1
)

for /f "tokens=*" %%v in ('python --version 2^>^&1') do echo [OK] Found %%v

echo.
echo [*] Installing gTTS (Google Text-to-Speech) ...
python -m pip install --quiet --upgrade gTTS
if errorlevel 1 (
    echo [ERROR] pip install failed. Check your internet connection.
    pause
    exit /b 1
)
echo [OK] gTTS ready.

if not exist "regen_audio.py" (
    echo [ERROR] regen_audio.py not found in this folder.
    pause
    exit /b 1
)

echo.
echo [*] Synthesising MP3s (takes about 1 minute) ...
echo.
python regen_audio.py
if errorlevel 1 (
    echo.
    echo [ERROR] regen_audio.py failed. See messages above.
    pause
    exit /b 1
)

echo.
echo [OK] Done. Opening deck.html in your browser ...
if exist "deck.html" (
    start "" "deck.html"
) else (
    echo [warn] deck.html not found - open it manually.
)

echo.
echo ============================================================
echo  All done. Audio plays inside the flip-cards.
echo  Keyboard: left/right arrows, space to flip, S to shuffle.
echo ============================================================
echo.
pause
endlocal
'''

REGEN_SH_TEMPLATE = r'''#!/usr/bin/env bash
# ============================================================
#  Arabic flashcards - one-click audio generator (macOS/Linux)
#  Run: bash regen_audio.sh   (or ./regen_audio.sh once +x)
#  Requires: python3 on PATH.
# ============================================================

set -e
cd "$(dirname "$0")"

echo
echo "============================================================"
echo " Arabic Flashcards - Audio Generator"
echo " Deck folder: $PWD"
echo "============================================================"
echo

if ! command -v python3 >/dev/null 2>&1; then
    echo "[ERROR] python3 is not installed or not on PATH."
    echo "        macOS:   brew install python   (or https://www.python.org/downloads/)"
    echo "        Linux:   sudo apt install python3 python3-pip"
    exit 1
fi

echo "[OK] Found $(python3 --version)"
echo
echo "[*] Installing gTTS ..."
python3 -m pip install --quiet --upgrade --user gTTS || {
    echo "[ERROR] pip install failed. Check your internet connection."
    exit 1
}
echo "[OK] gTTS ready."

if [ ! -f "regen_audio.py" ]; then
    echo "[ERROR] regen_audio.py not found in this folder."
    exit 1
fi

echo
echo "[*] Synthesising MP3s (takes about 1 minute) ..."
echo
python3 regen_audio.py

echo
echo "[OK] Done. Opening deck.html ..."
if [ -f "deck.html" ]; then
    if command -v open >/dev/null 2>&1; then
        open deck.html
    elif command -v xdg-open >/dev/null 2>&1; then
        xdg-open deck.html
    else
        echo "[info] No opener found - open deck.html manually."
    fi
fi

echo
echo "============================================================"
echo " All done. Audio plays inside the flip-cards."
echo " Keyboard: left/right arrows, space to flip, S to shuffle."
echo "============================================================"
'''


def log(msg: str) -> None:
    print(msg, flush=True)


def synth_gtts(text: str, out_path: Path, lang: str = "ar") -> tuple[bool, str]:
    try:
        from gtts import gTTS  # type: ignore
    except ImportError:
        return False, "gTTS not installed (pip install gTTS)"
    try:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        gTTS(text=text, lang=lang, slow=False).save(str(out_path))
        # gTTS sometimes leaves 0-byte files on partial failure — guard.
        if out_path.exists() and out_path.stat().st_size == 0:
            out_path.unlink()
            return False, "gTTS wrote 0-byte file"
        return True, ""
    except Exception as exc:  # network / quota / unsupported chars
        # Remove any 0-byte remnant gTTS may have created before failing.
        try:
            if out_path.exists() and out_path.stat().st_size == 0:
                out_path.unlink()
        except OSError:
            pass
        return False, str(exc)


def synth_elevenlabs(text: str, out_path: Path, voice: str) -> tuple[bool, str]:
    api_key = os.environ.get("ELEVENLABS_API_KEY")
    if not api_key:
        return False, "ELEVENLABS_API_KEY not set"
    try:
        from elevenlabs.client import ElevenLabs  # type: ignore
    except ImportError:
        return False, "elevenlabs client not installed"
    try:
        client = ElevenLabs(api_key=api_key)
        audio_stream = client.text_to_speech.convert(
            voice_id=voice,
            model_id="eleven_multilingual_v2",
            text=text,
            output_format="mp3_44100_128",
        )
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with out_path.open("wb") as f:
            for chunk in audio_stream:
                if chunk:
                    f.write(chunk)
        return True, ""
    except Exception as exc:
        return False, str(exc)


def generate_one(text: str, out_path: Path, provider: str, voice: str) -> tuple[bool, str]:
    if provider == "elevenlabs":
        ok, err = synth_elevenlabs(text, out_path, voice)
        if ok:
            return True, ""
        ok, gerr = synth_gtts(text, out_path)
        return ok, err if ok else f"{err}; gTTS fallback: {gerr}"
    return synth_gtts(text, out_path)


def emit_regen_script(deck_dir: Path) -> list[Path]:
    """Write standalone recovery scripts alongside the manifest.

    Emits three files so users on any OS have a one-click path:
      regen_audio.py   — cross-platform Python runner
      regen_audio.bat  — Windows one-click wrapper (installs gTTS, runs .py, opens deck.html)
      regen_audio.sh   — macOS/Linux one-click wrapper (same flow)
    """
    targets: list[Path] = []

    py_path = deck_dir / "regen_audio.py"
    py_path.write_text(REGEN_SCRIPT_TEMPLATE, encoding="utf-8")
    try:
        py_path.chmod(0o755)
    except OSError:
        pass
    targets.append(py_path)

    bat_path = deck_dir / "regen_audio.bat"
    # Windows line endings for .bat (cmd.exe is happier with CRLF)
    bat_path.write_text(REGEN_BAT_TEMPLATE.replace("\n", "\r\n"), encoding="utf-8")
    targets.append(bat_path)

    sh_path = deck_dir / "regen_audio.sh"
    sh_path.write_text(REGEN_SH_TEMPLATE, encoding="utf-8")
    try:
        sh_path.chmod(0o755)
    except OSError:
        pass
    targets.append(sh_path)

    return targets


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate MP3 audio for an Arabic flashcard deck.")
    ap.add_argument("--manifest", required=True, help="Path to cards.json")
    ap.add_argument("--out", required=True, help="Output directory for mp3 files")
    ap.add_argument("--variety", choices=["najdi", "msa"], default="msa",
                    help="Deck variety (affects log messages only — synthesis always uses Arabic text)")
    ap.add_argument("--provider", choices=["gtts", "elevenlabs"], default="gtts")
    ap.add_argument("--voice", default="Rachel", help="Voice name/id for ElevenLabs")
    ap.add_argument("--verbose", action="store_true")
    ap.add_argument("--no-regen-script", action="store_true",
                    help="Don't write a standalone regen_audio.py on failure.")
    args = ap.parse_args()

    manifest_path = Path(args.manifest)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    if not manifest_path.exists():
        log(f"[error] manifest not found: {manifest_path}")
        return 2

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    cards = manifest.get("cards", [])
    if not cards:
        log("[error] manifest has no cards.")
        return 2

    log(f"[info] variety={args.variety}  provider={args.provider}  cards={len(cards)}")
    if args.variety == "najdi" and args.provider == "gtts":
        log("[note] gTTS has no native Najdi voice — audio will approximate MSA pronunciation.")

    success = 0
    failures: list[tuple[str, str]] = []  # (filename, reason)
    expected = 0
    first_error_printed = False

    for card in cards:
        slug = card.get("slug")
        if not slug:
            log("[warn] card missing slug; skipping.")
            continue

        jobs = []
        if card.get("arabic"):
            jobs.append((card["arabic"], out_dir / f"{slug}.mp3"))
        for i, sent in enumerate(card.get("sentences", []), start=1):
            if sent.get("ar"):
                jobs.append((sent["ar"], out_dir / f"{slug}_ex{i}.mp3"))

        for text, path in jobs:
            expected += 1
            if args.verbose:
                log(f"[audio] {path.name}  ←  {text[:60]}")
            ok, err = generate_one(text, path, args.provider, args.voice)
            if ok:
                success += 1
            else:
                failures.append((path.name, err))
                if not first_error_printed:
                    log(f"[warn] first synthesis failure: {path.name}  ({err})")
                    first_error_printed = True

    # Summary + recovery plan
    log("")
    log(f"✓ {success}/{expected} files synthesised → {out_dir}")

    if failures:
        log(f"✗ {len(failures)} files failed (first error shown above).")
        if args.provider == "gtts" and any("google" in err.lower() or "connect" in err.lower() for _, err in failures):
            log("[hint] gTTS couldn't reach translate.google.com — common in sandboxed environments.")

        if not args.no_regen_script:
            deck_dir = manifest_path.parent
            regen_paths = emit_regen_script(deck_dir)
            log(f"[recovery] wrote standalone regen scripts in {deck_dir}:")
            for p in regen_paths:
                log(f"           - {p.name}")
            log(f"[recovery] on an unrestricted network:")
            log(f"             Windows : double-click regen_audio.bat")
            log(f"             macOS   : bash regen_audio.sh")
            log(f"             Linux   : bash regen_audio.sh")
            log(f"             Any OS  : pip install gTTS && python regen_audio.py")

    return 0 if not failures else 1


if __name__ == "__main__":
    sys.exit(main())
