#!/usr/bin/env python3
"""Generate MP3 audio for an Arabic training plan.

Reads a words.json manifest, synthesises audio for each headword and each
example sentence, and writes MP3 files to the output directory.

Providers:
    gtts        - default, free, no API key (pip install gTTS)
    elevenlabs  - higher quality, requires ELEVENLABS_API_KEY
                  (pip install elevenlabs)

Network-restricted environments:
    If gTTS cannot reach translate.google.com (common in sandboxed
    environments with allowlists), no silent placeholders are written.
    Instead, three recovery scripts are dropped next to the manifest
    (regen_audio.bat / regen_audio.sh / regen_audio.py) so the user
    can regenerate audio on a machine with normal internet access.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import textwrap
from pathlib import Path

# Force UTF-8 on stdout/stderr so Arabic chars don't crash Windows cp1252 consoles.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")  # Python 3.7+
    except (AttributeError, OSError):
        pass


REGEN_PY_TEMPLATE = r'''#!/usr/bin/env python3
"""Regenerate MP3 audio for this Arabic training plan using gTTS.

Auto-generated by the arabic-training-plan plugin when sandbox synthesis failed.
Run on a machine with normal internet access.

Requirements:
    pip install gTTS

Usage:
    python regen_audio.py
"""
import json
import sys
from pathlib import Path

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):
        pass

try:
    from gtts import gTTS
except ImportError:
    print("gTTS not installed. Run:  pip install gTTS")
    sys.exit(1)

HERE = Path(__file__).parent
MANIFEST = HERE / "words.json"
AUDIO_DIR = HERE / "audio"
AUDIO_DIR.mkdir(exist_ok=True)

LANG = "ar"  # Modern Standard Arabic voice (closest match for Najdi too)


def synth(text, out):
    gTTS(text=text, lang=LANG, slow=False).save(str(out))


def main():
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    words = data.get("words", [])
    n = 0
    for w in words:
        slug = w["slug"]
        synth(w["arabic"], AUDIO_DIR / f"{slug}.mp3"); n += 1
        for i, s in enumerate(w.get("sentences", []), start=1):
            synth(s["ar"], AUDIO_DIR / f"{slug}_ex{i}.mp3"); n += 1
        print(f"  {slug}")
    print(f"\n[OK] {n} MP3 files in {AUDIO_DIR}")


if __name__ == "__main__":
    main()
'''

REGEN_BAT_TEMPLATE = r'''@echo off
REM One-click audio regeneration for Windows.
REM Double-click this file after the plugin finished building the plan.
setlocal
cd /d "%~dp0"

where python >nul 2>nul
if errorlevel 1 (
    echo Python not found. Install Python 3 from https://www.python.org/ and re-run.
    pause
    exit /b 1
)

python -m pip install --quiet gTTS
if errorlevel 1 (
    echo Failed to install gTTS. Check your internet connection.
    pause
    exit /b 1
)

python regen_audio.py
if errorlevel 1 (
    echo Audio generation failed.
    pause
    exit /b 1
)

echo.
echo Done. Audio MP3s are in the audio\ folder.
pause
'''

REGEN_SH_TEMPLATE = r'''#!/usr/bin/env bash
# One-click audio regeneration for macOS / Linux.
set -e
cd "$(dirname "$0")"

if ! command -v python3 >/dev/null 2>&1; then
    echo "python3 not found. Install Python 3 and re-run."
    exit 1
fi

python3 -m pip install --quiet gTTS
python3 regen_audio.py

echo
echo "Done. Audio MP3s are in the audio/ folder."
'''


def load_manifest(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        print(f"[err] manifest not found: {path}", file=sys.stderr)
        sys.exit(2)
    except json.JSONDecodeError as e:
        print(f"[err] manifest is not valid JSON: {e}", file=sys.stderr)
        sys.exit(2)


def cleanup_empty(audio_dir: Path) -> int:
    """Remove 0-byte MP3 remnants from a previous failed run."""
    removed = 0
    if not audio_dir.exists():
        return 0
    for mp3 in audio_dir.glob("*.mp3"):
        try:
            if mp3.stat().st_size == 0:
                mp3.unlink()
                removed += 1
        except OSError:
            pass
    return removed


def drop_recovery_scripts(manifest_dir: Path) -> None:
    (manifest_dir / "regen_audio.py").write_text(REGEN_PY_TEMPLATE, encoding="utf-8")
    (manifest_dir / "regen_audio.bat").write_text(REGEN_BAT_TEMPLATE, encoding="utf-8")
    sh_path = manifest_dir / "regen_audio.sh"
    sh_path.write_text(REGEN_SH_TEMPLATE, encoding="utf-8")
    try:
        sh_path.chmod(0o755)
    except OSError:
        pass


def synth_gtts(text: str, out: Path) -> None:
    from gtts import gTTS  # local import so --help works without the dep
    gTTS(text=text, lang="ar", slow=False).save(str(out))


def synth_elevenlabs(text: str, out: Path, voice: str = "Rachel") -> None:
    from elevenlabs.client import ElevenLabs  # type: ignore
    key = os.environ.get("ELEVENLABS_API_KEY")
    if not key:
        raise RuntimeError("ELEVENLABS_API_KEY not set")
    client = ElevenLabs(api_key=key)
    audio = client.generate(text=text, voice=voice, model="eleven_multilingual_v2")
    with open(out, "wb") as f:
        for chunk in audio:
            f.write(chunk)


def main() -> int:
    p = argparse.ArgumentParser(
        description="Synthesise MP3s for an arabic-training-plan words.json"
    )
    p.add_argument("--manifest", required=True, help="path to words.json")
    p.add_argument("--out", required=True, help="output directory for MP3s")
    p.add_argument(
        "--provider", choices=("gtts", "elevenlabs"), default="gtts",
        help="TTS provider (default: gtts)",
    )
    p.add_argument("--voice", default="Rachel", help="ElevenLabs voice (if used)")
    p.add_argument(
        "--no-regen-script", action="store_true",
        help="do not drop regen_audio recovery scripts on failure",
    )
    args = p.parse_args()

    manifest_path = Path(args.manifest).resolve()
    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    data = load_manifest(manifest_path)
    words = data.get("words") or []
    if not words:
        print("[err] manifest has no 'words' array", file=sys.stderr)
        return 2

    if args.provider == "gtts":
        try:
            import gtts  # noqa: F401
        except ImportError:
            print(
                "[err] gTTS not installed.  pip install gTTS --break-system-packages",
                file=sys.stderr,
            )
            return 3
        synth = synth_gtts
    else:
        try:
            import elevenlabs  # noqa: F401
        except ImportError:
            print(
                "[err] elevenlabs SDK not installed.  pip install elevenlabs",
                file=sys.stderr,
            )
            return 3

        def synth(text: str, out: Path) -> None:  # type: ignore
            synth_elevenlabs(text, out, args.voice)

    total = 0
    failed = 0
    for w in words:
        slug = w["slug"]
        targets: list[tuple[str, Path]] = [(w["arabic"], out_dir / f"{slug}.mp3")]
        for i, s in enumerate(w.get("sentences", []), start=1):
            targets.append((s["ar"], out_dir / f"{slug}_ex{i}.mp3"))
        for text, outfile in targets:
            total += 1
            try:
                synth(text, outfile)
                print(f"  [ok]  {outfile.name}")
            except Exception as e:  # noqa: BLE001
                failed += 1
                print(f"  [fail] {outfile.name}: {e}", file=sys.stderr)

    # Cleanup 0-byte remnants regardless
    removed = cleanup_empty(out_dir)
    if removed:
        print(f"[cleanup] removed {removed} zero-byte MP3 remnant(s)")

    if failed:
        print(
            f"\n[warn] {failed}/{total} items failed — writing recovery scripts "
            f"next to the manifest.",
            file=sys.stderr,
        )
        if not args.no_regen_script:
            drop_recovery_scripts(manifest_path.parent)
            print(
                textwrap.dedent(
                    f"""
                    Recovery scripts written to {manifest_path.parent}:
                      - regen_audio.py   (any OS)
                      - regen_audio.bat  (Windows: double-click)
                      - regen_audio.sh   (macOS/Linux: chmod +x && ./regen_audio.sh)
                    Re-run on a machine with unrestricted internet.
                    """
                ).strip(),
                file=sys.stderr,
            )
        return 4

    print(f"\n[OK] {total} MP3 files written to {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
